// client/components/entries.vue
<template>
  <div v-if="props.data && props.data.items">
    <n-grid x-gap="12" :cols="props.cols" :y-gap="10">
      <n-grid-item v-for="entry in props.data.items" :key="entry.id">
        <Entry :entry="entry" />
      </n-grid-item>
    </n-grid>
  </div>
  <div v-else>
    <n-text>Loading...</n-text>
  </div>
</template>

<script setup lang="ts">
import { NGrid, NGridItem, NText } from 'naive-ui'
import type { ListResponse, PublicEntry } from '@tbd/common'
import Entry from './entry.vue'

const props = defineProps({
  data: Object as PropType<ListResponse<PublicEntry>>,
  cols: {
    type: Number,
    default: 4,
  },
})
</script>

// client-react/src/components/entries.tsx
import { SimpleGrid } from '@chakra-ui/react'
import type { ListResponse, PublicEntry } from '@tbd/common'
import Entry from '@/components/entry'

export default function Entries(props: { data: ListResponse<PublicEntry> | undefined; cols: number }) {
  console.log(props)
  const entries = function (items: PublicEntry[]) {
    return items.map(entry => <Entry key={entry.id} entry={entry} isEntryPage={false} />)
  }

  return props.data && props.data.items ? (
    <SimpleGrid templateColumns={`repeat(${props.cols}, 1fr)`} gap={4}>
      {entries(props.data.items)}
    </SimpleGrid>
  ) : (
    <p>Loading...</p>
  )
}
