// client-react/src/components/user.tsx
import { Text } from '@chakra-ui/react'
import { PublicUser } from '@tbd/common'

export default function User(props: { user?: PublicUser }) {
  const username = () => {
    if (props.user && props.user.username) return props.user.username
    return 'Unknown'
  }
  return <Text>{username()}</Text>
}

// client/components/user.vue
<template>
  <n-text>
    <b>{{ username }}</b>
  </n-text>
</template>

<script setup lang="ts">
import { NText } from 'naive-ui'
import type { PublicUser } from '@tbd/common'

const props = defineProps({
  user: Object as PropType<PublicUser>,
})

const username = computed(() => {
  if (props.user && props.user.username) return props.user.username
  return 'Unknown'
})
</script>
